modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ModdingForBlockheads/GravelMiner/issues"
[[mods]]
modId="gravelminer"
version="${file.jarVersion}"
displayName="GravelMiner"
displayURL="https://blay09.net/mods/gravelminer"
logoFile="gravelminer-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Automatically (insta-)mines falling gravel blocks that get in your way while mining.
'''
[[dependencies.gravelminer]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gravelminer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
