modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ModdingForBlockheads/GravelMiner/issues"

[[mods]]
modId="gravelminer"
version="${file.jarVersion}"
displayName="GravelMiner"
displayURL="https://blay09.net/mods/gravelminer"
logoFile="gravelminer-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Automatically (insta-)mines falling gravel blocks that get in your way while mining.
'''

[[dependencies.gravelminer]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gravelminer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gravelminer]]
    modId="balm"
    mandatory=true
    versionRange="[2.1.0,)"
    ordering="NONE"
    side="BOTH"
