modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ModdingForBlockheads/GravelMiner/issues"

[[mods]]
modId="gravelminer"
version="${file.jarVersion}"
displayName="GravelMiner"
displayURL="https://blay09.net/mods/gravelminer"
logoFile="gravelminer-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Automatically (insta-)mines falling gravel blocks that get in your way while mining.
'''

[[dependencies.gravelminer]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gravelminer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gravelminer]]
    modId="balm"
    mandatory=true
    versionRange="[4.0.0,)"
    ordering="NONE"
    side="BOTH"
