modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/blay09/GravelMiner/issues"
displayURL="https://minecraft.curseforge.com/projects/gravelminer"
authors="BlayTheNinth"

[[mods]]
modId="gravelminer"
version="${file.jarVersion}"
displayName="GravelMiner"
description='''
Automatically (insta-)mines falling gravel blocks that get in your way while mining.
'''
